### ISSUE TITLE
Funkmodul?

### ISSUE THREAD

**Issue by gagagu** [KaiGrassnick/thermotec_aeroflow#5]
Hallo, sorry dass ich diesen Bereich für meine Frage nutze, ich hoffe es ist für sie okay?

Ich habe eine Aeroflow Heizung mit der FlexiSmart LCD Steuerung an der Heizung, also ohne Funkmodul. Ich wollte mir jetzt noch mehr Geräte kaufen und diese dann per Home Assistant steuern. Ich habe ein paar Zigbee Fenstersensoren und ich kaufe noch Temperatursensoren dazu.
Nun meine Frage,
kann ich den FlexiSmart Heizkörper mit Home Assistant (und ihrem Modul) so nutzen oder brauche ich die Heizung mit dem Funkmodul oder auch noch die Smart Home Box?
Ich finde das alles etwas verwirrend und würde mich über einenGipp dazu sehr freuen.

Vielen Dank im Voraus!!!

**Comment by KaiGrassnick** [comment]
Moin

Das "Internetmodul für FlexiSmart" wird benötigt. Ansonsten müsste man das RF Protokoll reverse Engineeren und dann einen eigenen Sender dafür bauen. Diese Modul steuert das "Internetmodul für FlexiSmart" an. Im prinzip so, wie es die APP fürs Handy macht, nur eben direkt aus HomeAssistant raus.

Also: Heizkörper mit LCD (FlexiSmart) und Internetmodul für FlexiSmart. Ich denke mal, dass dir nur das Internetmodul fehlt.

**Comment by gagagu** [comment]
Vielen Dank für die Info!
