### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by maikdm** [KaiGrassnick/thermotec_aeroflow#6]
Tolle Integration. Hat bisher super funktioniert, nur leider habe ich seit ein paar Tagen ein Fehler, den ich nicht beheben kann. Neu laden der Integration bleibt erfolglos. Haben Sie eine Idee, was ich tun kann, um das zu beheben?
Hier das Protokoll:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/thermotec_aerowflow/__init__.py:56
Integration: thermotec_aerowflow
First occurred: 7. Mai 2023 um 13:51:49 (2 occurrences)
Last logged: 10:06:42

Error setting up entry Thermotec AeroFlow® FlexiSmart Gateway for thermotec_aeroflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/thermotec_aerowflow/__init__.py", line 56, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by ramsbeck** [comment]
Hi,
you can change line 56 in the "__init__.py" to this:

await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)

worked for me with the current 2023.10.0 release

**Comment by maikdm** [comment]
Thank you very much, it works again

**Comment by xsawa32** [comment]
same problem, solution works. thank you ramsbeck and KaiGrassnick for this Home Assistant Integration

**Comment by KaiGrassnick** [comment]
@maikdm Thank you for the issue. Sadly i completely missed the notification for this.
@EugenMayer Thank you for you fix. Its now released as version 0.0.5
