### ISSUE TITLE
Home Assistant - 2024.4.3 - Setup Error

### ISSUE THREAD

**Issue by noex** [KaiGrassnick/thermotec_aeroflow#8]
Using Home Assistant 2024.4.3 and the latest Version 0.0.5.

The Installation is fine, however while setting up the following error occurs: {"message":"Invalid handler specified"}

Any sugesstions?

**Comment by KaiGrassnick** [comment]
Thank you for you issue, i'll try to reproduce your error in the next days and will hopefully have more informations for you afterwards.

Could you provide a bit more information about your setup?
like: Are you using a standalone installation of HASSIO or one of the HASSIO images?

**Comment by noex** [comment]
I'm using VirtualBox Image on Windows 11.

![21b88cab-106d-45ea-95a9-16936cf08035](https://github.com/KaiGrassnick/thermotec_aeroflow/assets/638542/222b6f86-f7b8-4bde-bd45-3b677149d6f1)
![d3cb66eb-cce9-4559-bb96-0b3f095aeac7](https://github.com/KaiGrassnick/thermotec_aeroflow/assets/638542/a15ed718-066b-49b9-9c8e-be3cb6a4b7a1)

**Comment by KaiGrassnick** [comment]
@noex could you please verify, that the folder you placed inside the `custom_components` folder is named `thermotec_aeroflow` without the version number etc.

**Comment by noex** [comment]
@KaiGrassnick i'm very sorry, of course this was the mistake. after i renamed the folder, everything works as expected.

**Comment by KaiGrassnick** [comment]
Thank you for your final feedback. I'll update the README to make it clearer ;)
